doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App\Modules\User\Model\MongoDB:
                    dir: '%kernel.project_dir%/src/Modules/User/Model/MongoDB'
                    prefix: 'App\Modules\User\Model\MongoDB'
                App\Modules\OrganizationalUnit\Model\MongoDB:
                    dir: '%kernel.project_dir%/src/Modules/OrganizationalUnit/Model/MongoDB'
                    prefix: 'App\Modules\OrganizationalUnit\Model\MongoDB'
                App\Modules\League\Model\MongoDB:
                    dir: '%kernel.project_dir%/src/Modules/League/Model/MongoDB'
                    prefix: 'App\Modules\League\Model\MongoDB'
                App\Modules\Team\Model\MongoDB:
                    dir: '%kernel.project_dir%/src/Modules/Team/Model/MongoDB'
                    prefix: 'App\Modules\Team\Model\MongoDB'
                App\Modules\Season\Model\MongoDB:
                    dir: '%kernel.project_dir%/src/Modules/Season/Model/MongoDB'
                    prefix: 'App\Modules\Season\Model\MongoDB'
                App\Modules\SeasonTeam\Model\MongoDB:
                    dir: '%kernel.project_dir%/src/Modules/SeasonTeam/Model/MongoDB'
                    prefix: 'App\Modules\SeasonTeam\Model\MongoDB'
                App\Modules\Round\Model\MongoDB:
                    dir: '%kernel.project_dir%/src/Modules/Round/Model/MongoDB'
                    prefix: 'App\Modules\Round\Model\MongoDB'
                App\Modules\Game\Model\MongoDB:
                    dir: '%kernel.project_dir%/src/Modules/Game/Model/MongoDB'
                    prefix: 'App\Modules\Game\Model\MongoDB'
                App\Modules\GameEvent\Model\MongoDB:
                    dir: '%kernel.project_dir%/src/Modules/GameEvent/Model/MongoDB'
                    prefix: 'App\Modules\GameEvent\Model\MongoDB'
                App\Modules\Article\Model\MongoDB:
                    dir: '%kernel.project_dir%/src/Modules/Article/Model/MongoDB'
                    prefix: 'App\Modules\Article\Model\MongoDB'

when@prod:
    doctrine_mongodb:
        auto_generate_proxy_classes: false
        auto_generate_hydrator_classes: false
        document_managers:
            default:
                metadata_cache_driver:
                    type: service
                    id: doctrine_mongodb.system_cache_pool

    framework:
        cache:
            pools:
                doctrine_mongodb.system_cache_pool:
                    adapter: cache.system
