doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Modules\User\Model\MariaDB:
                dir: '%kernel.project_dir%/src/Modules/User/Model/MariaDB'
                prefix: 'App\Modules\User\Model\MariaDB'
            App\Modules\OrganizationalUnit\Model\MariaDB:
                dir: '%kernel.project_dir%/src/Modules/OrganizationalUnit/Model/MariaDB'
                prefix: 'App\Modules\OrganizationalUnit\Model\MariaDB'
            App\Modules\League\Model\MariaDB:
                dir: '%kernel.project_dir%/src/Modules/League/Model/MariaDB'
                prefix: 'App\Modules\League\Model\MariaDB'
            App\Modules\Team\Model\MariaDB:
                dir: '%kernel.project_dir%/src/Modules/Team/Model/MariaDB'
                prefix: 'App\Modules\Team\Model\MariaDB'
            App\Modules\Season\Model\MariaDB:
                dir: '%kernel.project_dir%/src/Modules/Season/Model/MariaDB'
                prefix: 'App\Modules\Season\Model\MariaDB'
            App\Modules\SeasonTeam\Model\MariaDB:
                dir: '%kernel.project_dir%/src/Modules/SeasonTeam/Model/MariaDB'
                prefix: 'App\Modules\SeasonTeam\Model\MariaDB'
            App\Modules\Round\Model\MariaDB:
                dir: '%kernel.project_dir%/src/Modules/Round/Model/MariaDB'
                prefix: 'App\Modules\Round\Model\MariaDB'
            App\Modules\Game\Model\MariaDB:
                dir: '%kernel.project_dir%/src/Modules/Game/Model/MariaDB'
                prefix: 'App\Modules\Game\Model\MariaDB'
        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
