nelmio_api_doc:
    documentation:
        securityDefinitions:
            username:

        info:
            title: Football Leagues API docs
            version: 0.0.1
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT

        security:
            - Bearer: []

        paths:
            /api/login:
                post:
                    tags:
                        - Authentication
                    description: Generate JWT.
                    security: [ ]
                    consumes:
                        - application/json
                    produces:
                        - application/json
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                            example: admin@admin.com
                                        password:
                                            type: string
                                            example: admin
                                    required:
                                        - username
                                        - password
                    responses:
                        '200':
                            description: Login successful
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                                example: "eyJ0eXAiOi..."
                        '401':
                            description: Login error
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            name:
                                                type: string
                                                example: "INVALID_CREDENTIALS"
                                            message:
                                                type: string
                                                example: "Invalid credentials, could not log you in."
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        host_patterns: # document only routes with a host of the form api.*
            - ^api\.
