version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./:/var/www/html/
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
    networks:
      - nginx_to_php
      - php_to_mariadb
      - php_to_mongodb
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    networks:
      - nginx_to_php

  # For now both databases are in one file
  # TODO: Separate them before performance testing
  mariadb:
    image: mariadb:10.11.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${DATABASE_NAME:-football_league}
      MYSQL_USER: ${DATABASE_USER:-user}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - php_to_mariadb

  mongodb:
    image: mongo:7.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
        - php_to_mongodb

volumes:
  mariadb_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  nginx_to_php:
    driver: bridge
  php_to_mariadb:
    driver: bridge
  php_to_mongodb:
    driver: bridge
