users:
    resource:
        path: ../src/Modules/User/
        namespace: App\Modules\User
    type: attribute

organizational_units:
    resource:
        path: ../src/Modules/OrganizationalUnit/
        namespace: App\Modules\OrganizationalUnit
    type: attribute

api_login_check:
    path: /api/login
