articles:
    resource:
        path: ../src/Modules/Article/
        namespace: App\Modules\Article
    type: attribute

games:
    resource:
        path: ../src/Modules/Game/
        namespace: App\Modules\Game
    type: attribute

game_events:
    resource:
        path: ../src/Modules/GameEvent/
        namespace: App\Modules\GameEvent
    type: attribute

leagues:
    resource:
        path: ../src/Modules/League/
        namespace: App\Modules\League
    type: attribute

organizational_units:
    resource:
        path: ../src/Modules/OrganizationalUnit/
        namespace: App\Modules\OrganizationalUnit
    type: attribute

season:
    resource:
        path: ../src/Modules/Season/
        namespace: App\Modules\Season
    type: attribute

season_team:
    resource:
        path: ../src/Modules/SeasonTeam/
        namespace: App\Modules\SeasonTeam
    type: attribute

round:
    resource:
        path: ../src/Modules/Round/
        namespace: App\Modules\Round
    type: attribute

teams:
    resource:
        path: ../src/Modules/Team/
        namespace: App\Modules\Team
    type: attribute

users:
    resource:
        path: ../src/Modules/User/
        namespace: App\Modules\User
    type: attribute

api_login_check:
    path: /api/login
