users:
    resource:
        path: ../src/Modules/User/
        namespace: App\Modules\User
    type: attribute

organizational_units:
    resource:
        path: ../src/Modules/OrganizationalUnit/
        namespace: App\Modules\OrganizationalUnit
    type: attribute

leagues:
    resource:
        path: ../src/Modules/League/
        namespace: App\Modules\League
    type: attribute

teams:
    resource:
        path: ../src/Modules/Team/
        namespace: App\Modules\Team
    type: attribute

api_login_check:
    path: /api/login
